image: alpine

stages:
  - "build"
  - "deploy"

Build:
  image: docker:20.10.13-dind-alpine3.15
  stage: build
  services:
    - docker:20.10.13-dind-alpine3.15
  only:
    - main
    - ci
  before_script:
    - apk add make bash build-base
    - . ./scripts/pre_build.sh
  script:
    - make build

Deploy:
  stage: deploy
  needs: ["Build"]
  only:
    - main
    - ci
  before_script:
    - apk add bash rsync openssh
    - . ./scripts/keys.sh
    - . ./scripts/server.sh
  script:
    - ssh $SERVER "cd $BASE_DIR && sh scripts/deploy.sh $LINGUANSKI_IMAGE $CI_COMMIT_SHORT_SHA $SERVER_URL && exit"
