version: "3.9"

services:
  api:
    image: ${LINGUANSKI_IMAGE}
    container_name: linguanski_api
    hostname: linguanski_api
    restart: always
    ports:
      - 8599:8599
    networks:
      - cluster
    environment:
      - SERVER_URL=${SERVER_URL}

networks:
  cluster:
    external: true
